version: "3"

services:
  api:
    container_name: washing_api
    image: 58040249104/washing_api:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - default

networks:
  default:
    external:
      name: db_network
